version: "3.9"

services:
  onlyfans:
    image: onlyfans:latest
    container_name: onlyfans
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: unless-stopped
    networks:
      - main
    stdin_open: true
    tty: true
    command: python start_ofd.py
    volumes:
      - ./settings/:/onlyfans/.settings
      - ./settings/profiles/:/onlyfans/.profiles
      - ./settings/sites/:/onlyfans/.sites

networks:
  main:
    name: main
    driver: bridge
